import com.server.bla.Server;
import com.server.bla.ServerOptions;
import com.server.bla.impl.FastServer;

import java.io.IOException;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jonhkr' at '5/5/16 8:21 PM' with Gradle 2.11
 *
 * @author jonhkr, @date 5/5/16 8:21 PM
 */
public class Library {

    public static void main(String args[]) throws IOException {
        Server server = new FastServer(new ServerOptions("0.0.0.0", 4000));

        server.listen();
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
